version: '3.4'

services:
  nodetest:
    image: craftytech/nodetest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
