
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: res-ingress-nx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx-res-svc
          servicePort: 8088

